### PR TITLE
53 angular

### PR DESCRIPTION
**Pull request by martinbreu**
applied

### CODE REVIEW

**Review by BjoernKrollGba — APPROVED** [review]

**Comment by martinbreu** [comment]
applied

**Comment by alexanderkiel** [comment]
Ich würde vor dem mergen noch auf das offizielle SL image gehen.

**Comment by martinbreu** [comment]
Waiting for UI image **samply/sample-locator:1.1.0**

**Comment by martinbreu** [comment]
new tag on master was created: https://github.com/samply/sample-locator/commits/v1.0.2
But in Dockerhub is only "latest": https://hub.docker.com/r/samply/sample-locator/tags

**Comment by martinbreu** [comment]
applied

**Pull request merged**
